const USER = "USER";
const USER_INFO_FETCH = "USER_INFO_FETCH";
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_FAILURE = "SIGNIN_FAILURE";


export {
  USER,
  USER_INFO_FETCH,
  SIGNIN_SUCCESS,
  SIGNIN_FAILURE,
}
