const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
const ADD_USER = 'ADD_USER';
const ADD_USER_ERROR = 'ADD_USER_ERROR';
const LOADING = 'LOADING';
const IS_AUTHORIZED = 'IS_AUTHORIZED';
const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
const ROLE = 'ROLE';

export {
  SIGN_IN_SUCCESS,
  SIGN_OUT,
  SIGN_IN_ERROR,
  SIGN_OUT_ERROR,
  ADD_USER,
  ADD_USER_ERROR,
  LOADING,
  IS_AUTHORIZED,
  IS_AUTHENTICATED,
  ROLE
}
